name: ui_package
description: This Package Having UI Design And Function Auth ets.. & extensions & Icons
version: 0.3.0
homepage: http://hafezcodx.com

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.17.5
  dio: ^5.7.0
  easy_pdf_viewer: ^1.0.8
  easy_sidemenu: ^0.5.0
  firebase_auth: ^4.15.3
  firebase_database: ^10.5.7
  firebase_messaging: ^14.7.10
  firebase_notifications_handler: ^2.0.0+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.6
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - asset/icons/icon-3/
    - asset/icons/imageApp/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MaterialDesignIconFont
      fonts:
        - asset: asset/fonts/materialdesignicons-webfont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
flutter_assets:
  assets_path: asset/icons/imageApp/
  output_path: lib/constants/
  filename: assetImage.dart
  field_prefix: